# DB NameSpace Policy

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-isolation
  namespace: db
spec:
  podSelector: {} # namespace db 상 모드 pod 대상
  policyTypes:
  - Ingress
  ingress:
    - from :
      - namespaceSelector: {}

---
# App NameSpace Policy
#
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apply-isolation
  namespace: apply
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    # main에서 접근 가능
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: main
    # apply에서 내부 통신 허용 
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: apply
    # Ingress Controller (외부 트래픽) 허용
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - ipBlock:
        cidr: 172.100.100.13/32
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8000

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: result-isolation
  namespace: result
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    # main에서 접근 가능
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: main
    # result에서 내부 통신 허용 
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: result
    # Ingress Controller (외부 트래픽) 허용
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    # Apply에서 접근 가능
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: apply
    - ipBlock:
        cidr: 172.100.100.13/32
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8000

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: schedule-isolation
  namespace: schedule
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    # main에서 접근 가능
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: main
    # schedule에서 내부 통신 허용
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: schedule
    # Ingress Controller (외부 트래픽) 허용
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - ipBlock:
        cidr: 172.100.100.13/32
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8000


---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: admin-isolation
  namespace: admin
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    # main에서 접근 가능
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: admin-main
    # admin에서 내부 통신 허용
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: admin
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
  # Bastion Host로 부터 접속 허용
    - ipBlock:
        cidr: 172.100.100.13/32
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8000
