# Master의 서비스 생성
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-svc
spec:
  type: ExternalName
  externalName: 172.100.100.15 # 마스터 VM의 실제 IP
---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
data:
  # 1. 슬레이브 설정 (Master와 server-id가 달라야 함)
  my.cnf: |
    [mysqld]
    server-id = 2
    read_only = 1
    gtid_mode = ON
    enforce_gtid_consistency = ON
    log_bin = mysql-bin
    binlog_format = ROW
    skip_host_cache
    skip_name_resolve

  # 2. 복제 연결 설정 스크립트
  setup.sql: |
    CHANGE MASTER TO
      MASTER_HOST='172.100.100.15',
      MASTER_USER='repl_user',
      MASTER_PASSWORD='1234',
      MASTER_AUTO_POSITION=1,
      GET_MASTER_PUBLIC_KEY=1;
    START SLAVE;
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: initdb-volume
          mountPath: /docker-entrypoint-initdb.d/setup.sql
          subPath: setup.sql
      volumes:
      - name: config-volume
        configMap:
          name: mysql-slave-config
      - name: initdb-volume
        configMap:
          name: mysql-slave-config
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave-svc
spec:
  selector:
    app: mysql-slave
  ports:
    - protocol: TCP
      port: 3306      
      targetPort: 3306
  type: ClusterIP
