# 0. 각 파드에서 사용할 pv 생성 pvc는 생성하지 않음
# 각 노드에 메칭될 수 있도록 디렉토리 생성
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # <--- 이 이름을 추가 #########
  hostPath:
    path: /mnt/mysql-data-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # <--- 이 이름을 추가 #########
  hostPath:
    path: /mnt/mysql-data-1
---
# 1. Master의 서비스 생성 (ExternalName)
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-svc
spec:
  type: ExternalName
    externalName: 172.100.100.15 # 마스터 VM의 실제 IP
---
# 2. ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
data:
  my.cnf: |
    [mysqld]
    server-id = 2  # 주의: 복제본이 여러 개일 경우 실제로는 ID가 달라야 함
    read_only = 1
    gtid_mode = ON
    enforce_gtid_consistency = ON
    log_bin = mysql-bin
    binlog_format = ROW
    skip_host_cache
    skip_name_resolve

  setup.sql: |
    CHANGE MASTER TO
      MASTER_HOST='172.100.100.15',
      MASTER_USER='repl_user',
      MASTER_PASSWORD='1234',
      MASTER_AUTO_POSITION=1,
      GET_MASTER_PUBLIC_KEY=1;
    START SLAVE;
---
# 3. StatefulSet (2 Replicas, 10Gi PVC)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
spec:
  serviceName: "mysql-slave-svc"
  replicas: 2
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: initdb-volume
          mountPath: /docker-entrypoint-initdb.d/setup.sql
          subPath: setup.sql
      volumes:
      - name: config-volume
        configMap:
          name: mysql-slave-config
      - name: initdb-volume
        configMap:
          name: mysql-slave-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      storageClassName: manual  # pv와 맞춰주는게 가장 중요
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
# 4. Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave-svc
spec:
  selector:
    app: mysql-slave
  ports:
    - protocol: TCP
      port: 3306      
      targetPort: 3306
  type: ClusterIP
  externalIPs:
    - 172.100.100.15
