apiVersion: apps/v1
kind: Deployment
metadata:
  name: apply-fastapi-deployment
  namespace: apply
spec:
  replicas: 1
  selector: { matchLabels: { app: apply-fastapi } }
  template:
    metadata: { labels: { app: apply-fastapi } }
    spec:
      containers:
      - name: apply-fastapi
        image: jiwon888/fastapi:6.2
        ports: [{ containerPort: 8000 }]
        env:
        - name: MYSQL_HOST
          value: "mysql-cluster.db"
        - name: MYSQL_USER
          valueFrom: { secretKeyRef: { name: secret, key: mysql-user-id } }
        - name: MYSQL_PASSWORD
          valueFrom: { secretKeyRef: { name: secret, key: mysql-user-password } }
        - name: MYSQL_DB_1
          valueFrom: { secretKeyRef: { name: secret, key: mysql-database-1 } }
        - name: MYSQL_DB_2
          valueFrom: { secretKeyRef: { name: secret, key: mysql-database-2 } }
        - name: MYSQL_PORT_RW
          value: "6446"
        - name: MYSQL_PORT_RO
          value: "6447"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-fastapi-deployment
  namespace: schedule
spec:
  replicas: 1
  selector: { matchLabels: { app: schedule-fastapi } }
  template:
    metadata: { labels: { app: schedule-fastapi } }
    spec:
      containers:
      - name: schedule-fastapi
        image: jiwon888/fastapi:6.2
        ports: [{ containerPort: 8000 }]
        env:
        - name: MYSQL_HOST
          value: "mysql-cluster.db"
        - name: MYSQL_USER
          valueFrom: { secretKeyRef: { name: secret, key: mysql-user-id } }
        - name: MYSQL_PASSWORD
          valueFrom: { secretKeyRef: { name: secret, key: mysql-user-password } }
        - name: MYSQL_DB_1
          valueFrom: { secretKeyRef: { name: secret, key: mysql-database-1 } }
        - name: MYSQL_DB_2
          valueFrom: { secretKeyRef: { name: secret, key: mysql-database-2 } }
        - name: MYSQL_PORT_RW
          value: "6446"
        - name: MYSQL_PORT_RO
          value: "6447"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-fastapi-deployment
  namespace: result
spec:
  replicas: 1
  selector: { matchLabels: { app: result-fastapi } }
  template:
    metadata: { labels: { app: result-fastapi } }
    spec:
      containers:
      - name: result-fastapi
        image: jiwon888/fastapi:6.2
        ports: [{ containerPort: 8000 }]
        env:
        - name: MYSQL_HOST
          value: "mysql-cluster.db"
        - name: MYSQL_USER
          valueFrom: { secretKeyRef: { name: secret, key: mysql-user-id } }
        - name: MYSQL_PASSWORD
          valueFrom: { secretKeyRef: { name: secret, key: mysql-user-password } }
        - name: MYSQL_DB_1
          valueFrom: { secretKeyRef: { name: secret, key: mysql-database-1 } }
        - name: MYSQL_DB_2
          valueFrom: { secretKeyRef: { name: secret, key: mysql-database-2 } }
        - name: MYSQL_PORT_RW
          value: "6446"
        - name: MYSQL_PORT_RO
          value: "6447"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-fastapi-deployment
  namespace: admin
spec:
  replicas: 1
  selector: { matchLabels: { app: admin-fastapi } }
  template:
    metadata: { labels: { app: admin-fastapi } }
    spec:
      containers:
      - name: admin-fastapi
        image: jiwon888/fastapi:6.2
        ports: [{ containerPort: 8000 }]
        env:
        - name: MYSQL_HOST
          value: "mysql-cluster.db"
        - name: MYSQL_USER
          valueFrom: { secretKeyRef: { name: secret, key: mysql-user-id } }
        - name: MYSQL_PASSWORD
          valueFrom: { secretKeyRef: { name: secret, key: mysql-user-password } }
        - name: MYSQL_DB_1
          valueFrom: { secretKeyRef: { name: secret, key: mysql-database-1 } }
        - name: MYSQL_DB_2
          valueFrom: { secretKeyRef: { name: secret, key: mysql-database-2 } }
        - name: MYSQL_PORT_RW
          value: "6446"
        - name: MYSQL_PORT_RO
          value: "6447"
---
apiVersion: v1
kind: Service
metadata: { name: apply-fastapi-service, namespace: apply }
spec:
  selector: { app: apply-fastapi }
  ports: [{ port: 80, targetPort: 8000 }]
---
apiVersion: v1
kind: Service
metadata: { name: schedule-fastapi-service, namespace: schedule }
spec:
  selector: { app: schedule-fastapi }
  ports: [{ port: 80, targetPort: 8000 }]
---
apiVersion: v1
kind: Service
metadata: { name: result-fastapi-service, namespace: result }
spec:
  selector: { app: result-fastapi }
  ports: [{ port: 80, targetPort: 8000 }]
---
apiVersion: v1
kind: Service
metadata: { name: admin-fastapi-service, namespace: admin }
spec:
  selector: { app: admin-fastapi }
  ports: [{ port: 80, targetPort: 8000 }]
