# Deploy
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apply-fastapi-deployment
  namespace: apply
  labels:
    app: apply-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apply-fastapi
  template:
    metadata:
      labels:
        app: apply-fastapi
    spec:
      containers:
      - name: apply-fastapi
        image: jiwon888/fastapi:4.3
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
        env:
        - name: MYSQL_HOST
          value: "mysql-cluster.db"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-user-id
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-user-password
        - name: MYSQL_DB_1
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database-1
        - name: MYSQL_DB_2
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database-2
        - name: MYSQL_PORT_RW
          value: "3306"
        - name: MYSQL_PORT_RO
          value: "3306"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-fastapi-deployment
  namespace: schedule
  labels:
    app: schedule-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-fastapi
  template:
    metadata:
      labels:
        app: schedule-fastapi
    spec:
      containers:
      - name: schedule-fastapi
        image: jiwon888/fastapi:4.3
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: "mysql-cluster.db"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-user-id
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-user-password
        - name: MYSQL_DB_1
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database-1
        - name: MYSQL_DB_2
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database-2
        - name: MYSQL_PORT_RW
          value: "3306"
        - name: MYSQL_PORT_RO
          value: "3306"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-fastapi-deployment
  namespace: result
  labels:
    app: result-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-fastapi
  template:
    metadata:
      labels:
        app: result-fastapi
    spec:
      containers:
      - name: result-fastapi
        image: jiwon888/fastapi:4.3
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
        env:
        - name: MYSQL_HOST
          value: "mysql-cluster.db"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-user-id
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-user-password
        - name: MYSQL_DB_1
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database-1
        - name: MYSQL_DB_2
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database-2
        - name: MYSQL_PORT_RW
          value: "3306"
        - name: MYSQL_PORT_RO
          value: "3306"
---

# Service

apiVersion: v1
kind: Service
metadata:
  name: apply-fastapi-service
  namespace: apply
spec:
  selector:
    app: apply-fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: schedule-fastapi-service
  namespace: schedule
spec:
  selector:
    app: schedule-fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: result-fastapi-service
  namespace: result
spec:
  selector:
    app: result-fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---
# HPA

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apply-fastapi-hpa
  namespace: apply
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apply-fastapi-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 50

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: result-fastapi-hpa
  namespace: result
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: result-fastapi-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

