apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
spec:
  secretName: secret
  instances: 3 # 3-node HA
  router:
    instances: 1 # Router 1개

  # configMap 설정
  podSpec:
    containers:
    - name: mysql
      # TimeOut 최적화
      readinessProbe:
        exec:
          command: ["/readinessprobe.sh"]
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 10
      livenessProbe:
        exec:
          command: ["/livenessprobe.sh"]
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 10
      volumeMounts:
      - name: init-sql
        mountPath: /docker-entrypoint-initdb.d
    volumes:
    - name: init-sql
      configMap:
        name: mysql-configmap

  tlsUseSelfSigned: true
  datadirVolumeClaimTemplate:
    storageClassName: manual
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 5G # 각 노드 당 2G 디스크
