apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
  namespace: default
  annotations:
    # ArgoCD가 모든 리소스를 배포한 후에 이 Job을 실행하도록 설정
    argocd.argoproj.io/hook: PostSync
    # 다음 배포 때 이전에 실행된 Job을 자동으로 지우고 새로 실행
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:8.0
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Waiting for MySQL to be ready..."
            # MySQL이 응답할 때까지 최대 2분간 대기
            for i in {1..24}; do
              if mysql -h mysql-cluster -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1" >/dev/null 2>&1; then
                echo "MySQL is up! Running init.sql..."
                mysql -h mysql-cluster -u root -p${MYSQL_ROOT_PASSWORD} < /docker-entrypoint-initdb.d/init.sql
                echo "Initialization complete."
                exit 0
              fi
              echo "Retrying in 5 seconds..."
              sleep 5
            done
            echo "Failed to connect to MySQL."
            exit 1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: rootPassword
        volumeMounts:
        - name: init-sql-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql-volume
        configMap:
          name: mysql-configmap # 기존에 만들어진 ConfigMap 이름 사용
      restartPolicy: OnFailure