apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
spec:
  secretName: secret
  instances: 3
  router:
    instances: 1
  tlsUseSelfSigned: true

  # Pod 설정 최적화
  podSpec:
    containers:
    - name: mysql
      # 오퍼레이터가 관리하는 기본 프로브를 덮어쓰게 됩니다.
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 10
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 10
      volumeMounts:
      - name: init-sql
        mountPath: /docker-entrypoint-initdb.d
    volumes:
    - name: init-sql
      configMap:
        name: mysql-configmap

  # PVC 템플릿 (spec 추가됨)
  datadirVolumeClaimTemplate:
    spec:
      storageClassName: manual
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5G
