apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: db
spec:
  secretName: secret
  instances: 3 # 3-node HA
  router:
    instances: 1 # Router 1개
  tlsUseSelfSigned: true
  mycnf: |
    [mysqld]
    loose-group_replication_member_expel_timeout=60
    loose-group_replication_autorejoin_tries=3
    connect_timeout=30
    innodb_lock_wait_timeout=100

  podSpec:
    containers:
    - name: mysql
      resources:
        requests:
          cpu: "500m"
          memory: "1G"
        limits:
          cpu: "1"
          memory: "2G"

      # [수정] postStart 훅 제거: NFS 지연 시 파드 사망 방지 및 초기화 Job으로 기능 분리
      startupProbe:
        exec:
          command: ["/livenessprobe.sh", "8"]
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 15
        failureThreshold: 100 # 넉넉하게 설정 (최대 500초)
      readinessProbe:
        exec:
          command: ["/readinessprobe.sh"]
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 10
      livenessProbe:
        exec:
          command: ["/livenessprobe.sh"]
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 10
  datadirVolumeClaimTemplate:
    storageClassName: manual
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 5G # 각 노드 당 5G 디스크
